Repository sb02-HRBank-team01/sb02-HRBank-team01, pull requests merged in 2025-04, with the labels that each got.

#41 [한성태 | 0422] Feature/22 직원 등록 엔티티 및 레포지토리 구현
  src/main/java/com/team01/hrbank/constraint/EmployeeStatus.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/repository/EmployeeStatusRepository.java
Labels: Todo, 직원, sub_issue

#45 [한성태 | 0422] Feature/23 직원 등록 서비스 로직 및 맵퍼 컴포넌트 응답 객체 구현
  src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeDto.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/mapper/EmployeeMapper.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/EmployeeStatusRepository.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#56 [한성태 | 0423] Feature/26 직원 등록 컨트롤러 구현
  .gitignore
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeDto.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/exception/DuplicateDepartmentNameException.java
  src/main/java/com/team01/hrbank/exception/DuplicateException.java
  src/main/java/com/team01/hrbank/repository/DepartmentRepository.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/DepartmentServiceImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#69 [한성태 | 0423] Feature/58 직원 조회 contoller 구현
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
Labels: Todo, 직원, sub_issue

#73 [한성태 | 0423] Feature/71 유저 상세 조회 service 구현
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#74 [한성태 | 0423] Feature/72 직원 상세 조회 controller 구현
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/converter/EmployeeStatusConverter.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/mapper/EmployeeMapper.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#82 [한성태 | 0423] Feature/80 직원 삭제 service 구현
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#83 [한성태 | 0423] Feature/81 직원 삭제 관련 API 구현 및 테스트 완료
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
Labels: Todo, 직원, sub_issue

#87 [한성태 | 0424] Feature/85 직원 수정 service 로직 구현
  src/main/java/com/team01/hrbank/constraint/EmployeeStatus.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeUpdateRequest.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#90 [윤영로 | 0424] Feature/36 직원정보 이력 목록 조회 기능 구현(Entity, Repository, DTO, Mapper 구성)
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/dto/changelog/ChangeLogDto.java
  src/main/java/com/team01/hrbank/dto/changelog/CursorPageResponseChangeLogDto.java
  src/main/java/com/team01/hrbank/entity/ChangeLog.java
  src/main/java/com/team01/hrbank/entity/ChangeLogDetail.java
  src/main/java/com/team01/hrbank/enums/ChangeType.java
  src/main/java/com/team01/hrbank/mapper/ChangeLogMapper.java
  src/main/java/com/team01/hrbank/repository/ChangeLogRepository.java
  src/main/resources/static/HR_BANK API 명세.json
Labels: 이력, sub_issue

#92 [한성태 | 0424] Feature/86 직원 수정 contoller 구현 및 테스트 완료
  images/2
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/converter/EmployeeStatusConverter.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeUpdateRequest.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#94 [한성태 | 0424] Feature/46 직원 등록 테스트
  images/2
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
Labels: Todo, 직원, sub_issue

#100 [한성태 | 0424] Feature/98 직원 수 추이 조회 service 구현
  .gitignore
  src/main/java/com/team01/hrbank/converter/EmployeeStatusConverter.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeTrendDto.java
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/enums/EmployeeStatus.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#105 [한성태 | 0424] Feature/103 직원 분포 조회 service 구현 및 QeuryDsl 환경
  .gitignore
  build.gradle
  src/main/java/com/team01/hrbank/config/AppConfig.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeDistributionDto.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#106 [한성태 | 0424] Feature/104 직원 분포 조회 api 구현 및 예외처리 추가 및 테스트 수행
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/enums/TimeUnit.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#110 [한성태 : 0425] Feature/108 직원 수 조회 비즈니스 로직 및 repo 구현
  src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#111 [한성태 | 0425] Feature/109 직원수 조회 api 구현 및 테스트 진행
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java
Labels: Todo, 직원, sub_issue

#114 [윤영로 | 0425] Feature/113 직원 정보 수정 이력 목록 조회
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/dto/changelog/CursorPageResponseChangeLogDto.java
  src/main/java/com/team01/hrbank/dto/changelog/DiffDto.java
  src/main/java/com/team01/hrbank/entity/ChangeLogDetail.java
  src/main/java/com/team01/hrbank/mapper/ChangeLogMapper.java
  src/main/java/com/team01/hrbank/repository/ChangeLogDetailRepository.java
  src/main/java/com/team01/hrbank/repository/ChangeLogRepository.java
  src/main/java/com/team01/hrbank/repository/custom/ChangeLogQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogQueryRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/ChangeLogService.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
Labels: Todo, 이력, sub_issue

#116 [윤영로 | 0425] (직원 정보 수정 이력 관리) 직원 정보 수정 이력 상세 조회 구현
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogQueryRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/ChangeLogService.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
Labels: Todo, 이력, sub_issue

#120 [윤영로 | 0425] Feature/91 수정 이력 건수 조회
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/repository/custom/ChangeLogQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
  src/main/java/com/team01/hrbank/repository/impl/DepartmentRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/ChangeLogService.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
Labels: Todo, 이력, sub_issue

#121 [한성태 | 0425] Feature/112 직원 목록 조회 service 및 repository 고도화 진행
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/dto/employee/CursorPageResponseEmployeeDto.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/EmployeeService.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, sub_issue

#124 [한성태 | 0425] Fixed/122 직원 관리 직원에 대한 repository 고도화
  src/main/java/com/team01/hrbank/dto/employee/CursorPageRequestEmployeeDto.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
  src/main/java/com/team01/hrbank/dto/employee/EmployeeUpdateRequest.java
  src/main/java/com/team01/hrbank/enums/EmployeeStatus.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, main_issue

#125 [윤영로 | 0426] Feature/119 changelog save 구현 및 exception 처리 추가
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/controller/ChangeLogTestController.java
  src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/team01/hrbank/entity/ChangeLog.java
  src/main/java/com/team01/hrbank/entity/ChangeLogDetail.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
  src/main/java/com/team01/hrbank/util/DiffUtil.java
Labels: 이력, sub_issue

#127 [윤영로 | 0426] Fix CursorUtil 삭제로 인한 수정
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
Labels: 이력

#131 [한성태 | 0426] Feature/129 조회 조건 설정 추가
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, main_issue

#133 [한성태 | 0427] (직원 관리) Fixed/132 직원 수 추이 조회, 직원 수 조회 조회 시 조건 추가
  src/main/java/com/team01/hrbank/controller/EmployeeController.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, main_issue

#135 [윤영로 | 0427] Bug/134 change logs sort
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/entity/ChangeLog.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
  src/main/resources/static/HR_BANK API 명세.json
Labels: 이력, sub_issue

#141 [윤영로 | 0427] Fix/139 change log 관련 파일 정리
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/dto/changelog/DiffDto.java
  src/main/java/com/team01/hrbank/entity/ChangeLog.java
  src/main/java/com/team01/hrbank/entity/ChangeLogDetail.java
  src/main/java/com/team01/hrbank/mapper/ChangeLogMapper.java
  src/main/java/com/team01/hrbank/repository/ChangeLogDetailRepository.java
  src/main/java/com/team01/hrbank/repository/ChangeLogRepository.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/ChangeLogService.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
Labels: 이력, main_issue

#142 [양찬혁|0427] (수정) 실패 시에 상태 안 뜨는 오류 수정
  src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/team01/hrbank/exception/BackupFailedException.java
  src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
Labels: sub_issue

#143 [양찬혁|0427] (백업수정)에러발생 주석처리
  src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
Labels: sub_issue

#144 [양찬혁|0427] (백업수정)서비스 로직 추가
  src/main/java/com/team01/hrbank/repository/BackupRepository.java
  src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
Labels: sub_issue

#145 Fixed/employee 관련 기능 코드 정리
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, main_issue

#146 [양찬혁|0248] (수정) 바이너리, 백업 최종 수정 완료
  src/main/java/com/team01/hrbank/entity/Backup.java
  src/main/java/com/team01/hrbank/exception/BackupFailedException.java
  src/main/java/com/team01/hrbank/repository/BackupRepository.java
  src/main/java/com/team01/hrbank/repository/BinaryContentRepository.java
  src/main/java/com/team01/hrbank/repository/impl/BackupRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/BackupService.java
  src/main/java/com/team01/hrbank/service/BinaryContentService.java
  src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
  src/main/java/com/team01/hrbank/storage/BinaryContentStorage.java
  src/main/java/com/team01/hrbank/storage/BinaryContentStorageImpl.java
  src/main/java/com/team01/hrbank/storage/CsvBackupStorage.java
  src/main/java/com/team01/hrbank/storage/CsvBackupStorageImpl.java
Labels: Todo, 파일, 백업, sub_issue

#150 [윤영로 | 0428] Fix ChangeLog관련 파일 수정
  src/main/java/com/team01/hrbank/controller/ChangeLogController.java
  src/main/java/com/team01/hrbank/dto/changelog/DiffDto.java
  src/main/java/com/team01/hrbank/entity/ChangeLog.java
  src/main/java/com/team01/hrbank/repository/custom/ChangeLogQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/ChangeLogService.java
  src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java
Labels: 이력, main_issue

#151 사원번호 부여시 조건 변경
  src/main/java/com/team01/hrbank/entity/Employee.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: Todo, 직원, main_issue

#153 [양찬혁 | 0428] (수정) 최종수정
  build.gradle
  images/.gitkeep
  src/main/java/com/team01/hrbank/controller/BinaryContentController.java
  src/main/java/com/team01/hrbank/entity/BaseEntity.java
  src/main/java/com/team01/hrbank/entity/BaseUpdatableEntity.java
  src/main/java/com/team01/hrbank/repository/BackupRepository.java
  src/main/java/com/team01/hrbank/repository/custom/BackupQueryRepository.java
  src/main/java/com/team01/hrbank/repository/impl/BackupRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/BackupService.java
  src/main/java/com/team01/hrbank/service/BinaryContentService.java
  src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
  src/main/java/com/team01/hrbank/service/impl/BinaryContentServiceImpl.java
  src/main/java/com/team01/hrbank/storage/BinaryContentStorage.java
  src/main/java/com/team01/hrbank/storage/BinaryContentStorageImpl.java
  src/main/resources/application.yml
  src/test/java/com/team01/hrbank/HrBankApplicationTests.java
Labels: sub_issue

#156 refactor: 백업 기능 전체 구조 수정 및 파일 저장 방식 통합
  .gitignore
  images/image.txt
  src/main/java/com/team01/hrbank/controller/BackupController.java
  src/main/java/com/team01/hrbank/controller/BinaryContentController.java
  src/main/java/com/team01/hrbank/converter/EmployeeStatusConverter.java
  src/main/java/com/team01/hrbank/dto/backup/BackupPageDto.java
  src/main/java/com/team01/hrbank/dto/backup/CursorRequest.java
  src/main/java/com/team01/hrbank/dto/binarycontent/BinaryContentDto.java
  src/main/java/com/team01/hrbank/entity/Backup.java
  src/main/java/com/team01/hrbank/entity/BinaryContent.java
  src/main/java/com/team01/hrbank/mapper/BinaryContentMapper.java
  src/main/java/com/team01/hrbank/repository/BinaryContentRepository.java
  src/main/java/com/team01/hrbank/repository/ChangeLogRepository.java
  src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
  src/main/java/com/team01/hrbank/repository/custom/BackupCustomRepository.java
  src/main/java/com/team01/hrbank/repository/impl/BackupRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/BackupService.java
  src/main/java/com/team01/hrbank/service/BinaryContentService.java
  src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
  src/main/java/com/team01/hrbank/service/impl/BinaryContentServiceImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
  src/main/java/com/team01/hrbank/storage/BinaryContentStorage.java
  src/main/java/com/team01/hrbank/storage/BinaryContentStorageImpl.java
  src/main/java/com/team01/hrbank/storage/CsvBackupStorage.java
  src/main/java/com/team01/hrbank/storage/CsvBackupStorageImpl.java
  src/main/java/com/team01/hrbank/storage/impl/BinaryContentStorageImpl.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: 백업, main_issue

#157 Fix: 월 단위로 마지막 날짜를 정확히 계산하도록 수정
  src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
  src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java
Labels: 직원, main_issue
